### ISSUE TITLE
[DEV] UI 개선 작업

### ISSUE THREAD

**Issue by pius338** [CAU-DM/DearMe_DEMO#14]
### Header 🤖
- [x] UserInfo 반응형UI 수정
- [x] About us 기능 추가
---
### Feed 📷
  - [x] 일기 없을 때 알림 수정
  - [x] 날짜 포맷 변경
---
### Chat 💬
  - [x] Generate버튼 가시성 높이기
  - [x] 메세지 보낸 시간 추가
  - [x] 날짜 알림 추가
  - [x] DropZone 말풍선 스타일 변경
  - [x] 메세지 줄높이 조정
---

**Comment by minseok128** [comment]
응원해요!!!🥑
