### ISSUE TITLE
[BUG] 예시일기가 생성되는 치명적인 문제

### ISSUE THREAD

**Issue by minseok128** [CAU-DM/DearMe_DEMO#34]
### 설명
- 무의미한 대화를 하는 경우에 예시 일기가 출력되어버리는 치명적인 문제가 있습니다.
> <img width="584" alt="image" src="https://github.com/CAU-DM/DearMe_DEMO/assets/27052038/b5410dac-b780-4318-be89-ca2a304540e2">

**Comment by cozy-hn** [comment]
이거 어떻게 고쳐요 선생님
