### ISSUE TITLE
[DEV] Demo 전까지 구현 (FrontEnd)

### ISSUE THREAD

**Issue by pius338** [CAU-DM/DearMe_DEMO#7]
### Header 🤖
- 로그아웃 버튼
---
### Feed 📷
- 피드 리디자인
- 피드에 데이터 띄우기
---
### Chat 💬
- Generate 버튼
- 사진 관련 기능
  - 사진 받는 말풍선
  - 사진 받고 채팅창 잠금
  - 사진 DB에 전송
- 일기 생성 완료 메세지 보낸 후 New diary 버튼 생성
- New diary 버튼 클릭 시 채팅창 clear, 대화 다시 시작
- 채팅창 자동 스크롤 기능
- 입력 창 자동 확장

**Comment by minseok128** [comment]
화이팅 응원해요🚀
