### ISSUE TITLE
[DEV] Demo 전까지 구현 (BackEnd)

### ISSUE THREAD

**Issue by minseok128** [CAU-DM/DearMe_DEMO#8]
- happy path
  - 유저 로그인
  - 유저가 10번 이상의 일상 대화를 진행
  - generate button 활성화됨
  - 버튼을 누르면 그동안의 모든 대화를 기반으로 서버는 일기를 생성 시작
  - 그 사이에 프론트에서 유저에게 사진을 받고 있음
  - 사진이 받아지면, 사진과 최종 완성된 일기를 피드에 띄움(디비에 저장 후 업데이트하는 방식)
  - 새일기 생성 버튼이 활성화됨
  - 새일기 생성 버튼 누를 시, 채팅창 clear, 다시 일상 대화 진행으로 시작(이때, DB는 새로운 대화에 맞는 element 생성되어있음)

- sad path
  - 유저 로그인
  - 기존에 일기가 완성되지 않은 미완성 대화가 있음(DB에서 마지막 element의 일기 컬럼 원소가 null인 경우)
  - 미완성 대화를 불러오고 대화 시작

**Comment by pius338** [comment]
화이팅 응원해요🚀
